DROP TABLE IF EXISTS "books",
"chapters",
"translations",
"testamentTranslations",
"bookTranslations",
"verses";

CREATE TABLE "books" (
	"id" TEXT NOT NULL PRIMARY KEY,
	"isNewTestament" BOOLEAN NOT NULL
);

CREATE TABLE "chapters" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"bookID" TEXT NOT NULL,
	"number" INTEGER NOT NULL,
	UNIQUE ("bookID", "number")
);

CREATE TABLE "translations" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"code" TEXT NOT NULL UNIQUE,
	"name" TEXT NOT NULL,
	"language" TEXT NOT NULL,
	"languageCode" CHAR(3) NOT NULL,
	"regionCode" CHAR(2) NOT NULL
);

CREATE TABLE "testamentTranslations" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"isNewTestament" BOOLEAN NOT NULL,
	"translationID" INTEGER NOT NULL,
	"name" TEXT NOT NULL,
	UNIQUE ("isNewTestament", "translationID")
);

CREATE TABLE "bookTranslations" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"bookID" TEXT NOT NULL,
	"translationID" INTEGER NOT NULL,
	"name" TEXT NOT NULL,
	UNIQUE ("bookID", "translationID")
);

CREATE TABLE "verses" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"chapterID" INTEGER NOT NULL,
	"translationID" INTEGER NOT NULL,
	"number" INTEGER NOT NULL,
	"text" TEXT NOT NULL,
	UNIQUE ("chapterID", "translationID", "number")
);

ALTER TABLE "chapters" ADD FOREIGN KEY ("bookID") REFERENCES "books" ("id");

ALTER TABLE "testamentTranslations" ADD FOREIGN KEY ("translationID") REFERENCES "translations" ("id");

ALTER TABLE "bookTranslations" ADD FOREIGN KEY ("bookID") REFERENCES "books" ("id"),
ADD FOREIGN KEY ("translationID") REFERENCES "translations" ("id");

ALTER TABLE "verses" ADD FOREIGN KEY ("chapterID") REFERENCES "chapters" ("id"),
ADD FOREIGN KEY ("translationID") REFERENCES "translations" ("id");
