DROP TABLE IF EXISTS "testaments",
"books",
"chapters",
"translations",
"testamentTranslations",
"bookTranslations",
"chapterTranslations",
"verses";

-- table for testaments (Old and New)
CREATE TABLE "testaments" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"isNewTestament" BOOLEAN NOT NULL
);

CREATE TABLE "books" (
	"id" TEXT NOT NULL PRIMARY KEY,
	"testamentID" INTEGER NOT NULL
);

CREATE TABLE "chapters" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"bookID" INTEGER NOT NULL,
	"number" INTEGER NOT NULL,
	UNIQUE ("bookID", "number")
);

CREATE TABLE "translations" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"code" TEXT NOT NULL UNIQUE,
	"name" TEXT NOT NULL,
	"language" TEXT NOT NULL,
	"languageCode" CHAR(2) NOT NULL,
	"regionCode" CHAR(2) NOT NULL
);

CREATE TABLE "testamentTranslations" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"testamentID" INTEGER NOT NULL,
	"translationID" INTEGER NOT NULL,
	"name" TEXT NOT NULL,
	UNIQUE ("testamentID", "translationID")
);

CREATE TABLE "bookTranslations" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"bookID" INTEGER NOT NULL,
	"translationID" INTEGER NOT NULL,
	"name" TEXT NOT NULL,
	UNIQUE ("bookID", "translationID")
);

CREATE TABLE "chapterTranslations" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"chapterID" INTEGER NOT NULL,
	"translationID" INTEGER NOT NULL,
	"name" TEXT NOT NULL,
	UNIQUE ("chapterID", "translationID")
);

CREATE TABLE "verses" (
	"id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"chapterID" INTEGER NOT NULL,
	"translationID" INTEGER NOT NULL,
	"number" INTEGER NOT NULL,
	"text" TEXT NOT NULL,
	UNIQUE ("chapterID", "translationID", "number")
);

ALTER TABLE "books" ADD FOREIGN KEY ("testamentID") REFERENCES "testaments" ("id");

ALTER TABLE "chapters" ADD FOREIGN KEY ("bookID") REFERENCES "books" ("id");

ALTER TABLE "testamentTranslations" ADD FOREIGN KEY ("testamentID") REFERENCES "testaments" ("id"),
ADD FOREIGN KEY ("translationID") REFERENCES "translations" ("id");

ALTER TABLE "bookTranslations" ADD FOREIGN KEY ("bookID") REFERENCES "books" ("id"),
ADD FOREIGN KEY ("translationID") REFERENCES "translations" ("id");

ALTER TABLE "chapterTranslations" ADD FOREIGN KEY ("chapterID") REFERENCES "chapters" ("id"),
ADD FOREIGN KEY ("translationID") REFERENCES "translations" ("id");

ALTER TABLE "verses" ADD FOREIGN KEY ("chapterID") REFERENCES "chapters" ("id"),
ADD FOREIGN KEY ("translationID") REFERENCES "translations" ("id");
